#!/usr/bin/python3

import os
import sys

print('Start to make ProLinux container...')

os.system('sudo apt-get -y install python3 python3-pip virtualenvwrapper')

print('\nVirtualenv setting start..!\n')

os.system('virtualenv -p /usr/bin/python3 venv')
os.system('. venv/bin/activate && pip install pychroot')

print('\nVirtualenv setting finish..!\n')
print('GO TO source venv/bin/activate & run gen_container_fs')
